mod quantum_hardware {
    use crate::utils::instructions::BasisGates;

    #[derive(PartialEq, Eq, Hash, Debug)]
    enum QuantumHardware {
        ALGIERS,
        ALMADEN,
        ARMONK,
        ATHENS,
        AUCKLAND,
        BELEM,
        BOEBLINGEN,
        BOGOTA,
        BRISBANE,
        BROOKLYN,
        BURLINGTON,
        CAIRO,
        CAMBRIDGE,
        CASABLANCA,
        CUSCO,
        ESSEX,
        FEZ,
        GENEVA,
        GUADALUPE,
        HANOI,
        JAKARTA,
        JOHANNESBURG,
        KAWASAKI,
        KOLKATA,
        KYIV,
        KYOTO,
        LAGOS,
        LIMA,
        LONDON,
        MAKARRESH,
        MELBOURNE,
        MANHATTAN,
        MANILA,
        MONTREAL,
        MUMBAI,
        NAIROBI,
        OSAKA,
        OSLO,
        OURENSE,
        PARIS,
        PERTH,
        POUGHKEEPSIE,
        PRAGUE,
        QUITO,
        ROCHESTER,
        ROME,
        SANTIAGO,
        SINGAPORE,
        SYDNEY,
        TORINO,
        TORONTO,
        VALENCIA,
        VIGO,
        WASHINGTON,
        YORKTOWN,
    }

    struct HardwareSpecification {
        quantum_hardware: QuantumHardware,
        basis_gates: BasisGates,
        num_qubits: u16, // number of qubits that a quantum hardware possess
        thermal_relaxation: bool,
    }
}
