mod quantum_hardware {
    use crate::utils::instructions::BasisGates;

    #[derive(PartialEq, Eq, Hash, Debug)]
    enum QuantumHardware {
        Algiers,
        Almaden,
        Armonk,
        Athens,
        Auckland,
        Belem,
        Boeblingen,
        Bogota,
        Brisbane,
        Brooklyn,
        Burlington,
        Cairo,
        Cambridge,
        Casablanca,
        Cusco,
        Esex,
        Fez,
        Geneva,
        Guadalupe,
        Hanoi,
        Jakarta,
        Johannesburg,
        Kawasaki,
        Kolkata,
        Kyiv,
        Kyoto,
        Lagos,
        Lima,
        London,
        Makarresh,
        Melbourne,
        Manhattan,
        Manila,
        Montreal,
        Mumbai,
        Nairobi,
        Osaka,
        Oslo,
        Ourense,
        Paris,
        Perth,
        Poughkeepsie,
        Prague,
        Quito,
        Rochester,
        Rome,
        Santiago,
        Singapore,
        Sydney,
        Torino,
        Toronto,
        Valencia,
        Vigo,
        Washington,
        Yorktown,
    }

    struct HardwareSpecification {
        quantum_hardware: QuantumHardware,
        basis_gates: BasisGates,
        num_qubits: u16, // number of qubits that a quantum hardware possess
        thermal_relaxation: bool,
    }
}
